version: '3'
services:
  receive:
    image: edwinlll/uchat2mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
    volumes:
      - ./.uchat2mq.yaml:/usr/local/uchat2mq/.uchat2mq.yaml
      - /etc/hosts:/etc/hosts
    command: ["receive"]
    expose:
      - 8800
    ports:
      - 8199:8800 
