version: '3'
services:
  uchat2mq:
    image: edwinlll/uchat2mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
    volumes:
      - ./.uchat2mq.yaml:/go/src/github.com/lvzhihao/uchat2mq/.uchat2mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone &&
      go-wrapper run receive"
    expose:
      - 8800
    ports:
      - 8199:8800 
